{"name": "test_less_than_5[9]", "status": "failed", "statusDetails": {"message": "AssertionError: Given number is greater than 5\nassert False", "trace": "self = <test_demo_report.TestDemoTwo object at 0x000002436E281A10>, data = 9\n\n    @pytest.mark.parametrize('data', [8, 4, 9])\n    def test_less_than_5(self, data):\n        if data < 5:\n            assert True\n        else:\n>           assert False, 'Given number is greater than 5'\nE           AssertionError: Given number is greater than 5\nE           assert False\n\ntest_demo_report.py:17: AssertionError"}, "parameters": [{"name": "data", "value": "9"}], "start": 1693137524234, "stop": 1693137524234, "uuid": "88da20b8-7d24-4033-bd85-a80bc48f7a41", "historyId": "433a5703985527dd167aa12a299ee9f3", "testCaseId": "bb7998be0affab3503054f8f966afd94", "fullName": "test_demo_report.TestDemoTwo#test_less_than_5", "labels": [{"name": "suite", "value": "test_demo_report"}, {"name": "subSuite", "value": "TestDemoTwo"}, {"name": "host", "value": "DESKTOP-G7A3TQO"}, {"name": "thread", "value": "35660-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_demo_report"}]}