{"name": "test_less_than_5[8]", "status": "failed", "statusDetails": {"message": "AssertionError: Given number is greater than 5\nassert False", "trace": "self = <test_demo_report.TestDemoTwo object at 0x000002436E2816D0>, data = 8\n\n    @pytest.mark.parametrize('data', [8, 4, 9])\n    def test_less_than_5(self, data):\n        if data < 5:\n            assert True\n        else:\n>           assert False, 'Given number is greater than 5'\nE           AssertionError: Given number is greater than 5\nE           assert False\n\ntest_demo_report.py:17: AssertionError"}, "parameters": [{"name": "data", "value": "8"}], "start": 1693137524227, "stop": 1693137524227, "uuid": "abaf637e-24a2-431b-aede-f0e5a2f58775", "historyId": "d551a10262304ebbecc3d4f2a7b5c821", "testCaseId": "bb7998be0affab3503054f8f966afd94", "fullName": "test_demo_report.TestDemoTwo#test_less_than_5", "labels": [{"name": "suite", "value": "test_demo_report"}, {"name": "subSuite", "value": "TestDemoTwo"}, {"name": "host", "value": "DESKTOP-G7A3TQO"}, {"name": "thread", "value": "35660-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_demo_report"}]}